# Generated by Django 5.1.3 on 2024-11-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0004_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
