# Generated by Django 5.1.3 on 2024-11-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0006_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
