# Generated by Django 5.1.3 on 2024-11-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
