# Generated by Django 5.1.3 on 2024-11-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0019_rentotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rentOTP',
        ),
    ]
