# Generated by Django 5.1.3 on 2024-12-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0025_rentotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rentOTP',
        ),
    ]
