# Generated by Django 5.1.3 on 2024-12-03 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0026_delete_rentotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='rentOTP',
            fields=[
                ('rentOTPid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('houseID', models.CharField(max_length=6)),
                ('ownerID', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
