# Generated by Django 5.1.3 on 2024-12-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0027_rentotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
