# Generated by Django 5.1.3 on 2024-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0029_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSell',
            fields=[
                ('hid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=100)),
                ('apartment', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('pimages', models.FileField(upload_to='')),
                ('emailId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateField()),
            ],
        ),
    ]
