# Generated by Django 5.1.3 on 2024-11-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_seller_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddRent',
        ),
    ]
