# Generated by Django 5.1.3 on 2024-11-28 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_seller_app', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrent',
            name='add_date',
            field=models.DateField(default=datetime.date(2024, 11, 28)),
        ),
    ]
