# Generated by Django 5.1.3 on 2024-11-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner_seller_app', '0008_alter_addrent_add_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddRent',
        ),
    ]
