# Generated by Django 5.1.3 on 2024-11-28 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner_seller_app', '0009_delete_addrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddRent',
            fields=[
                ('hid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('price', models.CharField(max_length=100)),
                ('apartment', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('pimages', models.FileField(upload_to='')),
                ('emailId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateField(default=datetime.date(2024, 11, 28))),
            ],
        ),
    ]
