# Generated by Django 5.1.3 on 2024-11-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_seller_app', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrent',
            name='add_date',
            field=models.DateField(),
        ),
    ]
